---
name: Checks

# This is the trigger, in our case, anytime we push changes to github.
on: [push]

jobs:
  test-lint:
    name: Test and Lint
    # The OS the job runs on
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        # Pre-made action provided in the Github Actions repo.
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"

